name: thememode_selector
description: A widget to select between light and dark ThemeMode (in development, but working fine)
version: 0.1.0
repository: https://github.com/BlueCowGroup/thememode_selector
homepage: https://github.com/BlueCowGroup/thememode_selector

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

